# Generated by Django 5.0 on 2023-12-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_estacionamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamiento',
            name='nombre_usuario',
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='nombre_usuario_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
