# Generated by Django 5.0 on 2023-12-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_remove_estacionamiento_nombre_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estacionamiento',
            table='Estacionaminto',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Trabajadores',
        ),
    ]
