# Generated by Django 5.0 on 2023-12-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_alter_estacionamiento_table_alter_usuario_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administracion',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('habitacion', models.CharField(max_length=50)),
                ('nombre_usuario_id', models.CharField(max_length=50)),
                ('tipo_usuario', models.CharField(choices=[('Visita', 'Visita'), ('Residente', 'Residente'), ('Externo', 'Externo')], max_length=20)),
                ('contacto', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Administracion',
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('Visita', 'Visita'), ('Residente', 'Residente'), ('Externo', 'Externo')], max_length=20),
        ),
    ]
