# Generated by Django 5.0 on 2023-12-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_administracion_alter_usuario_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=50, unique=True)),
                ('nueva', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Solicitud',
            },
        ),
    ]
